name: Test, Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0'
      - run: java --version
      - run: mvn -v
      - name: Build with Maven
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "<settings><servers><server><id>github</id><username>cnadjim</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn clean install