name: push-on-master

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-core:
    uses: bettor-league/reusable-workflow/.github/workflows/java-project.yml@master
    with:
      maven_command: 'clean deploy'
    secrets: inherit

  build-authentication-api:
    uses: bettor-league/reusable-workflow/.github/workflows/java-project.yml@master
    with:
      maven_module_name: 'authentication-api'
      maven_command: 'clean install'
      upload_artifact: true
    secrets: inherit